---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: concourse-headers
  namespace: concourse
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: networking.k8s.io/config
kind: Ingress
metadata:
  name: concourse
  namespace: concourse
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: concourse-concourse-headers@kubernetescrd
spec:
  tls:
    - hosts:
        - ci.r3t.io
      secretName: concourse-tls
  rules:
    - host: ci.r3t.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: concourse-web
                port:
                  number: 8080
